DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM audit_log
    WHERE action::text IN (
      'INVITATION_CREATED',
      'INVITATION_REVOKED',
      'INVITATION_CONSUMED',
      'INVITATION_UPDATED'
    )
    OR resource = 'invitation'
  ) THEN
    RAISE EXCEPTION
      'Refusing to remove legacy invitation audit actions while invitation-era audit rows remain';
  END IF;
END $$;

CREATE TYPE "AuditAction_new" AS ENUM (
  'LOGIN',
  'LOGOUT',
  'LOGIN_FAILED',
  'PORTAL_ADMISSION_CREATED',
  'PORTAL_ADMISSION_UPDATED',
  'PORTAL_ADMISSION_CLAIMED',
  'PORTAL_ADMISSION_REVOKED',
  'PORTAL_ADMISSION_RESET',
  'PENDING_CATALOG_GRANT_CREATED',
  'PENDING_CATALOG_GRANT_UPDATED',
  'PENDING_CATALOG_GRANT_REVOKED',
  'PENDING_CATALOG_GRANT_CONSUMED',
  'USER_ADDED',
  'USER_ACTIVATED',
  'USER_BLOCKED',
  'USER_UNBLOCKED',
  'USER_DELETED',
  'ADMIN_ROLE_GRANTED',
  'ADMIN_ROLE_REVOKED',
  'CATALOG_ACCESS_GRANTED',
  'CATALOG_ACCESS_UPDATED',
  'CATALOG_ACCESS_REVOKED',
  'CATALOG_CREATED',
  'CATALOG_UPDATED',
  'CATALOG_DEACTIVATED',
  'CATALOG_VIEWED',
  'AUDIO_STREAMED',
  'AUDIO_DOWNLOADED',
  'TRANSCRIPT_VIEWED',
  'TRANSCRIPT_DOWNLOADED',
  'METADATA_UPDATED',
  'METADATA_VERIFIED',
  'METADATA_DELETED',
  'ACCESS_DENIED',
  'SUPERADMIN_ACCESS'
);

ALTER TABLE "audit_log"
  ALTER COLUMN "action" TYPE "AuditAction_new"
  USING ("action"::text::"AuditAction_new");

DROP TYPE "AuditAction";

ALTER TYPE "AuditAction_new" RENAME TO "AuditAction";
