/**
 * Test fixture constants for E2E tests.
 *
 * These constants match the data seeded by prisma/seed-test.ts
 * and generated by scripts/generate-*.ts.
 */

import {
  TEST_CATALOG_ID,
  TEST_AUDIO_FILES,
  TEST_EVENTS,
  TEST_USERS,
  TEST_RECORDERS,
  TEST_LOCATIONS,
  padHash,
} from "../../../prisma/test-data";

export {
  TEST_CATALOG_ID,
  TEST_AUDIO_FILES,
  TEST_EVENTS,
  TEST_USERS,
  TEST_RECORDERS,
  TEST_LOCATIONS,
  padHash,
};

/**
 * Convenience array of just the full hashes
 */
export const TEST_AUDIO_HASHES = TEST_AUDIO_FILES.map((f) => f.hash);

/**
 * Get the first test audio file (most commonly used)
 */
export const FIRST_RECORDING = TEST_AUDIO_FILES[0];

/**
 * URL helpers for test navigation
 */
export const URLS = {
  signIn: "/auth/signin",
  unauthorized: "/auth/unauthorized",
  pending: "/auth/pending",
  blocked: "/auth/blocked",
  catalog: `/catalog/${TEST_CATALOG_ID}`,
  catalogEvents: `/catalog/${TEST_CATALOG_ID}?tab=events`,
  recording: (hash: string) => `/catalog/${TEST_CATALOG_ID}/recording/${hash}`,
  recordingEdit: (hash: string) => `/catalog/${TEST_CATALOG_ID}/recording/${hash}/edit`,
  event: (eventId: number) => `/catalog/${TEST_CATALOG_ID}/event/${eventId}`,
  catalogSettings: `/catalog/${TEST_CATALOG_ID}/settings`,
  settings: "/settings",
  admin: "/admin",
  adminCatalogs: "/admin/catalogs",
  adminMetadata: "/admin/metadata",
  adminMetadataLocations: "/admin/metadata/locations",
  adminMetadataRecorders: "/admin/metadata/recorders",
  adminMetadataAlbums: "/admin/metadata/albums",
  adminUsers: "/admin/users",
  adminPendingAdmissions: "/admin/users?status=PENDING", // Pending admissions are managed on the users page
  adminAudit: "/admin/audit",
} as const;
