-- Add new audit action values
ALTER TYPE "AuditAction" ADD VALUE 'USER_DELETED';
ALTER TYPE "AuditAction" ADD VALUE 'CATALOG_CREATED';
ALTER TYPE "AuditAction" ADD VALUE 'CATALOG_UPDATED';
ALTER TYPE "AuditAction" ADD VALUE 'CATALOG_DEACTIVATED';
ALTER TYPE "AuditAction" ADD VALUE 'METADATA_DELETED';

-- Remove ADMIN_ROLE_UPDATED by recreating the enum
-- Step 1: Create new enum without ADMIN_ROLE_UPDATED
CREATE TYPE "AuditAction_new" AS ENUM (
  'LOGIN',
  'LOGOUT',
  'LOGIN_FAILED',
  'INVITATION_CREATED',
  'INVITATION_REVOKED',
  'INVITATION_CONSUMED',
  'INVITATION_UPDATED',
  'USER_ADDED',
  'USER_ACTIVATED',
  'USER_BLOCKED',
  'USER_UNBLOCKED',
  'USER_DELETED',
  'ADMIN_ROLE_GRANTED',
  'ADMIN_ROLE_REVOKED',
  'CATALOG_ACCESS_GRANTED',
  'CATALOG_ACCESS_UPDATED',
  'CATALOG_ACCESS_REVOKED',
  'CATALOG_CREATED',
  'CATALOG_UPDATED',
  'CATALOG_DEACTIVATED',
  'CATALOG_VIEWED',
  'AUDIO_STREAMED',
  'AUDIO_DOWNLOADED',
  'TRANSCRIPT_VIEWED',
  'TRANSCRIPT_DOWNLOADED',
  'METADATA_UPDATED',
  'METADATA_VERIFIED',
  'METADATA_DELETED',
  'ACCESS_DENIED',
  'SUPERADMIN_ACCESS'
);

-- Step 2: Update column to use new enum
ALTER TABLE "audit_log" ALTER COLUMN "action" TYPE "AuditAction_new" USING ("action"::text::"AuditAction_new");

-- Step 3: Drop old enum
DROP TYPE "AuditAction";

-- Step 4: Rename new enum to original name
ALTER TYPE "AuditAction_new" RENAME TO "AuditAction";
